#shell script
before_script:
# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install

test:app:
  script:
  - phpunit --configuration phpunit.xml
